# permissions for end users to edit awsnoderefreshers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsnoderefresher-editor-role
rules:
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnoderefreshers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnoderefreshers/status
  verbs:
  - get
