# permissions for end users to view awsnodereplenishers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsnodereplenisher-viewer-role
rules:
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodereplenishers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodereplenishers/status
  verbs:
  - get
