# permissions for end users to view awsnoderefreshers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsnoderefresher-viewer-role
rules:
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnoderefreshers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnoderefreshers/status
  verbs:
  - get
