# permissions for end users to edit awsnodemanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsnodemanager-editor-role
rules:
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodemanagers/status
  verbs:
  - get
