# permissions for end users to view awsnodemanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsnodemanager-viewer-role
rules:
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodemanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodemanagers/status
  verbs:
  - get
