
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodemanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodereplenishers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodereplenishers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - nodemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - nodemanagers/status
  verbs:
  - get
  - patch
  - update
