apiVersion: operator.h3poteto.dev/v1alpha1
kind: NodeManager
metadata:
  name: nodemanager-sample
  namespace: default
spec:
  cloudProvider: aws
  aws:
    region: ap-northeast-1
    masters:
      desired: 3
      asgModifyCoolTimeSeconds: 300
      drainGracePeriodSeconds: 300
      refreshSchedule: "30 0 * * *"
      enableReplenish: false
      surplusNodes: 0
      autoScalingGroups:
        - name: master-ap-northeast-1a.masters.playground.k8s.h3poteto.dev
        - name: master-ap-northeast-1d.masters.playground.k8s.h3poteto.dev
        - name: master-ap-northeast-1c.masters.playground.k8s.h3poteto.dev
    workers:
      desired: 3
      asgModifyCoolTimeSeconds: 300
      drainGracePeriodSeconds: 300
      refreshSchedule: "30 * * * *"
      enableReplenish: false
      surplusNodes: 1
      autoScalingGroups:
        - name: nodes-ap-northeast-1a.playground.k8s.h3poteto.dev
        - name: nodes-ap-northeast-1d.playground.k8s.h3poteto.dev
        - name: nodes-ap-northeast-1c.playground.k8s.h3poteto.dev
